### ISSUE TITLE
Unhandled rejection Error: spawn \scripts\win32.bat ENOENT

### ISSUE THREAD

**Issue by GoorLavi** [mkorakakis/drive-scanner#2]
hey im working on electron project on a windows 10 64b pc.

im trying to run this code :
```
import DrivelistScanner from 'drivelist-scanner';

const scanner = new DrivelistScanner();

scanner.on('add', (drives) => console.log(drives));

scanner.on('remove', (drives) => console.log(drives));
```

and im getting this error each time interval is launched:

> Unhandled rejection Error: spawn \scripts\win32.bat ENOENT
>     at exports._errnoException (util.js:1050:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:367:16)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by GoorLavi** [comment]
sorry for opening this issue.
the problem was resolved by using elctron-rebuild.
